### PR TITLE
Demo selected state bookend

### PR DESCRIPTION
**Pull request by taysea**
[Deploy Preview](https://deploy-preview-4064--keen-mayer-a86c8b.netlify.app/components/select)

#### What does this PR do?
Demoing how we could use `box-shadow` for the selected state "bookend" since the background color alone wouldn't have enough contrast with the unselected background color.

#### What testing has been done on this PR?

In addition to the feature you are implementing, have you checked the following:

**General UX Checks**
- [ ] Small, medium, and large screen sizes
- [ ] Cross-browsers (FireFox, Chrome, and Safari)
- [ ] Light & dark modes
- [ ] All hyperlinks route properly

**Accessibility Checks**
- [ ] Keyboard interactions
- [ ] Screen reader experience
- [ ] Run WAVE accessibility plugin (Chrome)

**Code Quality Checks**
- [ ] Console is free of warnings and errors
- [ ] Passes E2E commit checks
- [ ] Visual snapshots are reasonable

#### Screenshots (if appropriate)

https://github.com/user-attachments/assets/3ea5ceb6-26b1-49f5-86fe-ac360d1f8328

https://github.com/user-attachments/assets/529e1ac0-f627-4c4a-8b07-131257d8d2ef

### CODE REVIEW

**Comment by oliverHPE** [comment]
Thanks @taysea 

To meet the guidelines for minimum contrast as found here: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum), let's make the width of the shadow 3px. That way the bookend would be considered thick (3 css pixels), and therefore the color contrast minimum would need to be 3 : 1, which the strong selected color is as measured against white.

**Comment by taysea** [comment]
> To meet the guidelines for minimum contrast as found here: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum), let's make the width of the shadow 3px. That way the bookend would be considered thick (3 css pixels), and therefore the color contrast minimum would need to be 3 : 1, which the strong selected color is as measured against white.

Updated!

**Review by oliverHPE — APPROVED** [review]
Looks good.

**Comment by taysea** [comment]
Closing, this theme update will be published with v1 tokens

**Pull request closed without merging**
