### PR TITLE
Updated whats new

### PR DESCRIPTION
**Pull request by halocline**
[Deploy Preview](https://deploy-preview-3334--keen-mayer-a86c8b.netlify.app/whats-new)

#### What does this PR do?

- Removes outdated links
- Adds "ways to engage"
- Adds missing notable enhancements
- Fixes internal site links to avoid page reloads

#### Where should the reviewer start?

What's New page

#### What testing has been done on this PR?

In addition to the feature you are implementing, have you checked the following:

**General UX Checks**
- [ ] Small, medium, and large screen sizes
- [ ] Cross-browsers (FireFox, Chrome, and Safari)
- [ ] Light & dark modes
- [ ] All hyperlinks route properly

**Accessibility Checks**
- [ ] Keyboard interactions
- [ ] Screen reader experience
- [ ] Run WAVE accessibility plugin (Chrome)

**Code Quality Checks**
- [ ] Console is free of warnings and errors
- [ ] Passes E2E commit checks
- [ ] Visual snapshots are reasonable

### CODE REVIEW

**Comment by SOjaHPE** [comment]
@halocline the new categorization buckets make it easy for our customers with different roles locate what is important to them. It also sheds light on other theme of deliverable types that function as a prompt to discover new resources they might have not known existed. The 'Ways to engage' is another means to expand our engagement and let customers pick which works best for them, based on synchronous or asynchronous due to timezone, etc.

**Comment by halocline** [comment]
> @halocline the new categorization buckets make it easy for our customers with different roles locate what is important to them. It also sheds light on other theme of deliverable types that function as a prompt to discover new resources they might have not known existed. The 'Ways to engage' is another means to expand our engagement and let customers pick which works best for them, based on synchronous or asynchronous due to timezone, etc.

I'm still playing with additional ways to position and highlight the value for our customers, but I think it is a step in the right direction. 

Next steps:
- Incorporate feedback and merge so we can get this to Jeff.
- Send the April portion to HPExs and HPE Design System stakeholders.

**Review by taysea — APPROVED** [review]
Looks great. thanks for adding the grommet-related work. I also like the addition of ways to engage section.

**Comment by SOjaHPE** [comment]
@halocline brainstorming..do you think it would be possible to relocate the 'opportunities to engage' to the right in a fixed panel in wider displays that is available as the user scrolls though the previous 'What's New' month to month details? Just a thought.. being at the top of the page and new release details always going below it isn't an issue. 

Another thought was to wrap the 'Opportunities to engage' in a section that has a slightly different typography feel to it so it doesn't blend in with the month to month release details.

**Comment by halocline** [comment]
> @halocline brainstorming..do you think it would be possible to relocate the 'opportunities to engage' to the right in a fixed panel in wider displays that is available as the user scrolls though the previous 'What's New' month to month details? Just a thought.. being at the top of the page and new release details always going below it isn't an issue.
> 
> Another thought was to wrap the 'Opportunities to engage' in a section that has a slightly different typography feel to it so it doesn't blend in with the month to month release details.

I do think there are opportunities to improve layout and the concept overall. In the spirit of "appetizer" sized portions, I didn't want to touch new layout or implementations (currently this page is just a markdown document). My priority is to get relevant, meaningful content in front our stakeholders in a timely manner (we have a lot of improvement to do on the timely portion).

**Comment by SOjaHPE** [comment]
@halocline thanks for making the updates, I approve the changes as is.

**Review by vavalos5 — APPROVED** [review]
LGTM, thanks for adding!

**Pull request merged**
