### PR TITLE
Page layouts

### PR DESCRIPTION
**Pull request by halocline**
[Deploy Preview](https://deploy-preview-2384--keen-mayer-a86c8b.netlify.app/templates/dashboards)

#### What does this PR do?

Merging PAGE-LAYOUTS branch into master. This merge encompasses all work associated with implementing the 3-Column Dashboard.

Work includes:
- Updated preview images for 2-column and 3-column dashboards.
- Adds the following data set mocks:
  - accounts.json
  - compliance.json
  - consumption.json
- Implements the 3-column dashboard including:
  - parent grid
  - cost by service
  - cost by month
  - cost by year
  - compliance audit results
- Reusable components for:
  - ChartCard
  - Legend
  - MeterGroup
- Utility functions for statistics, report windows, formatting currency, etc. 

#### Where should the reviewer start?

dashboards.mdx

#### What testing has been done on this PR?

In addition to the feature you are implementing, have you checked the following:

**General UX Checks**
- [x] Small, medium, and large screen sizes
- [x] Cross-browsers (FireFox, Chrome, and Safari)
- [x] Light & dark modes
- [x] All hyperlinks route properly

**Accessibility Checks**
- [ ] Keyboard interactions
- [ ] Screen reader experience
- [x] Run WAVE accessibility plugin (Chrome)

**Code Quality Checks**
- [x] Console is free of warnings and errors
- [x] Passes E2E commit checks
- [ ] Visual snapshots are reasonable

### CODE REVIEW

**Comment by britt6612** [comment]
Looks good code wise and preview link but the visual tests seem to be really off so I'm going to go through them and see if I see anything alarming

**Comment by halocline** [comment]
> Looks good code wise and preview link but the visual tests seem to be really off so I'm going to go through them and see if I see anything alarming

Related to a bug associated with adding the new `xsmall` breakpoint affecting the responsive nature of our AppNav. We resolved that yesterday and I have now updated snapshots accordingly.

**Comment by britt6612** [comment]
> > Looks good code wise and preview link but the visual tests seem to be really off so I'm going to go through them and see if I see anything alarming
> 
> Related to a bug associated with adding the new `xsmall` breakpoint affecting the responsive nature of our AppNav. We resolved that yesterday and I have now updated snapshots accordingly.

Thank you for the explanation I missed that yesterday 👍

**Review by britt6612 — APPROVED** [review]

**Review by taysea — APPROVED** [review]
LGTM!

**Pull request merged**
