### PR TITLE
Exploration/Feedback Requested — Show updated batch action behavior

### PR DESCRIPTION
**Pull request by taysea**
[Preview](https://deploy-preview-1714--keen-mayer-a86c8b.netlify.app/templates/filtering#filtering-with-selectable-results)

#### What does this PR do?
Demonstrating a version of batch actions to align with what is shown in [Figma](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A13926). Instead of having the search input and filter button persistent, instead when selections have been made those elements are replaced by a grey selections summary box.

Some considerations in my own experimentation with this pattern. What if I'm trying to use search as a mechanism to narrow in on results, make a selection, make a new search, add to my selections? With this pattern that is not possible. I am not familiar with users' typical searching/selecting behavior so maybe this should not be of concern, but figured I'd raise it as it was something I experienced when testing my work.

#### What are the relevant issues?
Related to #1676

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
> Some considerations in my own experimentation with this pattern. What if I'm trying to use search as a mechanism to narrow in on results, make a selection, make a new search, add to my selections? With this pattern that is not possible. I am not familiar with users' typical searching/selecting behavior so maybe this should not be of concern, but figured I'd raise it as it was something I experienced when testing my work.

Good comments. I seem to recall we felt that it was perilous to leave the search and filter active as it would be ambiguous what would happen to items selected that were no longer in the new search/filter. Would they still be selected even though not visible? How would the user know that? I think we were shooting for what seemed like and 80% case where the user could filter+search to get the set they wanted and then perform and action. This might be good guidance to add, as something to get feedback on.

**Comment by ericsoderberghp** [comment]
What about exploring a "feedback requested" or "actively exploring" annotation to try to highlight that we want to gather reactions?

**Comment by taysea** [comment]
Feedback from the HPE community in Slack: https://hpe.slack.com/archives/C04LMJWQT/p1625681947280800

## Areas of concern/Points of consideration
- **Action button(s) alignment:** Many folks are interested in the action buttons being left aligned. Because the main "next step" of selecting data is to take action against those selections, the feeling is that having the action buttons left aligned will make the buttons more visible, easier to access. The selection count would become a subtext below the actions and the "clear selection" button would come at the end of any actions.
- **What happens to persistent actions that appeared above the table when this banner appears?** Do they become part of the banner?  It seems that other UIs such as Gmail will hide persistent actions once a selection is made.
- **What is the 80/20 scenario for people searching/filtering, selecting, and then searching/filtering again?**

**Comment by taysea** [comment]
Closing for now, not currently relevant.

**Pull request closed without merging**
