### PR TITLE
Remove unnecessary elevation state

### PR DESCRIPTION
**Pull request by taysea**
[Deploy Preview](https://deploy-preview-2012--keen-mayer-a86c8b.netlify.app/)

#### What does this PR do?

Removes unnecessary state for Card now that this is being handled in theme.

#### Where should the reviewer start?

aries-site/src/components/cards/ContentCard.js

#### What testing has been done on this PR?

Tested the various layout cards on the site. Audited any place we were manually applying `large` elevation on hover.

In addition to the feature you are implementing, have you checked the following:
- [x] Console is free of warnings and errors
- [x] Light & dark modes
- [x] Small, medium, and large screen sizes
- [x] Cross-browsers (FireFox, Chrome, and Safari)
- [x] Keyboard interactions
- [x] Screen reader experience

#### How should this be manually tested?

Hover over the Cards on the homepage. Elevation should become `large`.

#### What are the relevant issues?

Related to https://github.com/grommet/grommet-theme-hpe/pull/221

#### Should this PR be mentioned in Design System updates?
Yes. Added hover elevation styles to Card.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Review by britt6612 — APPROVED** [review]
LGTM Good Clean up

**Comment by halocline** [comment]
FYI, our navigation tests began to break at some point yesterday:
```
1) Cannot obtain information about the node because the specified
      selector does not match any node in the DOM tree.

         | Selector('a')
       > |   .withText('Philosophy')
```

Seems likely related to the Card work we have been doing. Can we touch base this morning?

**Comment by britt6612** [comment]
> FYI, our navigation tests began to break at some point yesterday:
> 
> ```
> 1) Cannot obtain information about the node because the specified
>       selector does not match any node in the DOM tree.
> 
>          | Selector('a')
>        > |   .withText('Philosophy')
> ```
> 
> Seems likely related to the Card work we have been doing. Can we touch base this morning?

I can be available for a call @taysea if you have time

**Review by halocline — APPROVED** [review]
No concerns with code changes.

I would like to look at our E2E tests and Applitools.

**Comment by halocline** [comment]
> I would like to look at our E2E tests and Applitools.

The vast majority of the Applitools snapshot changes are related to a change in the Global footer's copyright. I had approved a bunch of these last week. Unsure why they did not save as the new baseline...

**Pull request merged**
