### PR TITLE
Some initial analytics logging

### LINKED ISSUE #2819: Make use of onAnalytics in Design System Site
Instrument Design System Site with onAnalytics
- [x] Update grommet dependency
- [x] Add `onAnalytics` to any `<Grommet>` tags (simple console.log for now)
- [ ] Add data/id attributes to any interesting forms or action buttons

See #2818

### PR DESCRIPTION
**Pull request by MikeKingdom**
Add an onAnalytics callback to Grommet to log some basic analytics info to the console.

The next step will be to connect this to Amplify or some other analytics system like Adobe or Google Analytics

[Deploy Preview](https://deploy-preview-2852--keen-mayer-a86c8b.netlify.app/)

closes #2819 

#### Where should the reviewer start?
ThemeMode.js

#### What testing has been done on this PR?

In addition to the feature you are implementing, have you checked the following:

**General UX Checks**
- [ ] Small, medium, and large screen sizes
- [ ] Cross-browsers (FireFox, Chrome, and Safari)
- [ ] Light & dark modes
- [ ] All hyperlinks route properly

**Accessibility Checks**
- [ ] Keyboard interactions
- [ ] Screen reader experience
- [ ] Run WAVE accessibility plugin (Chrome)

**Code Quality Checks**
- [ ] Console is free of warnings and errors
- [ ] Passes E2E commit checks
- [ ] Visual snapshots are reasonable

#### Should this PR be mentioned in Design System updates?
No

### CODE REVIEW

**Comment by halocline** [comment]
Implementation looks fine. Some things I am noticing:

- Content cards clicks are not picked up by onAnalytics. Our content cards are built with `<Card as="a" .../>`. Wondering how we might capture these events... Support some native HTML elements? Rethink how we are approaching clickable cards --> `<Button href=""><Card .../></Button>` instead?
- skipTo links layerOpen, layerClose events
- The importance of meaningful ids or other unique identifiers.
- Support for List `onClickItem`
- Means to present meaningful ancestor when the target is generic div, svg, text, etc.

I'll do some more investigating.

**Comment by MikeKingdom** [comment]
Thanks @halocline. I hadn't checked to see what that layer is really doing but it seemed odd that we did mount it. For the icon button targets and such I didn't find a clean way yet to get the best element ref given how the Button is constructed. 

In general we want nav or action types of events so I'm less sure about the List on click items and such. Note that you have to be extra careful not to actually send personal identifiable info to the real analytics engine (say a server hostname or IP or other selections etc.) With a list onClick it seems a bit too easy to accidentally send an overly identifiable key. Note that URLs have that danger too.

**Comment by halocline** [comment]
> In general we want nav or action types of events so I'm less sure about the List on click items and such. 

What about navigation occurring when I select an item from a list? For example, I have a collection of resources presented in a List and I want to navigate to the resource detail when I click on the particular list item. On the DS site, in the search experience, I would like to know which search result was selected and navigated to. Without that, we really only have pageView to and from, but no context as to what triggered that navigation.

**Comment by MikeKingdom** [comment]
> > In general we want nav or action types of events so I'm less sure about the List on click items and such.
> 
> What about navigation occurring when I select an item from a list? For example, I have a collection of resources presented in a List and I want to navigate to the resource detail when I click on the particular list item. On the DS site, in the search experience, I would like to know which search result was selected and navigated to. Without that, we really only have pageView to and from, but no context as to what triggered that navigation.

Isn't that typically an `<Anchor>` within the list item? Navigating from a row click would seem very odd. I know that's very true with DataTables (`<Anchor>` in a column cell).

**Review by halocline — APPROVED** [review]

**Pull request merged**
